---
title: "Urban Ocean Analysis 2023 "
output: html_notebook
---



```{r}

# Specific plotting tools
library(plotly)
library(ggpubr)
library(paletteer)
library(viridis)
library(cowplot)
library(leaflet)
library(readxl)
library(tidyverse)
source("Code/Functions.R")
```

# Preparations

Read in and merge sample data:

```{r}

# Sequencing data
ASV_12S <- read_csv("Data_import/MiFish-U_species_table.csv")  %>% 
  filter(Group != "Total") %>%  select(!Total)

# Sample metadata
VeDNA_UrbanOcean2023_sampledata <- read_excel("Data_import/VeDNA_UrbanOcean2023_sampledata.xlsx", 
    col_types = c("text", "text", "text", 
        "date", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "text", "numeric", "numeric", 
        "date", "text", "date", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "numeric", "text", "text", 
        "text"))

# Sequencing pool metadata
Sequencing_Pool_12S_VeDNA2023 <- read_excel("Data_import/Sequencing_Pool_12S-VeDNA2023.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "numeric", "text", "numeric", 
        "numeric", "numeric", "numeric")) %>% 
  filter(Pool_ID == "12S-VeDNA2023")

# Merge sample and library metadata
Sample_Data_12S <- VeDNA_UrbanOcean2023_sampledata %>% 
  right_join(Sequencing_Pool_12S_VeDNA2023, by = "Sample_ID") %>% 
  select(Library_ID, 1:15, 18, Library_Concentration, Volume_added) %>% 
  mutate(Type = ifelse(is.na(Type), "PCRBlank", Type))

# Merge metadata with sequencing data
OU_12S <- ASV_12S %>% 
  pivot_longer(!1:4, names_to = "Library_ID", values_to = "Abundance") %>% 
  left_join(Sample_Data_12S, by = "Library_ID") %>% 
  filter(is.na(Type) == FALSE)

```
Plot sequencing depth and remove bad samples.

```{r}
tmp <- OU_12S %>%
    group_by(Library_ID, Type) %>% 
    summarise(Library_Size = sum(Abundance)) %>% 
    arrange(Library_Size)
  
tmp$Index <- seq(nrow(tmp))

tmp %>% 
  ggplot() +
  geom_point(aes(Index, Library_Size,
                 colour = Type,
                 label = Library_ID),
             size = 0.5) +
  theme_cowplot(12) +
  theme(aspect.ratio = 1,
        strip.background =element_blank()) +
  geom_abline(intercept = 10000, linetype = 4)

ggsave("Figure_output/Sequencing_Depth.pdf", width = 7, height = 4.5)

Good_OU_12S <- OU_12S %>% 
  group_by(Library_ID) %>%
  filter(sum(Abundance)>10000) %>% 
  ungroup()

```
Index relative abundance:
```{r}

Indexed_UO_12S <- Good_OU_12S %>% 
  index_RA(sample = Library_ID,
           taxa = TaxonName,
           abundance = Abundance,
           Sample_Date, Station_ID, Location, Line_out_depth,
           Bottom_depth, Latitude, Longitude, Type)

Rank <- Indexed_UO_12S %>% 
  group_by(TaxonName) %>% 
  summarise(RA = mean(RA)) %>% 
  arrange(-RA) %>% 
  filter(RA > 0.0005)

Rank

```

```{r}

Indexed_UO_12S



Indexed_UO_12S %>%
  mutate(Month = factor(month(Sample_Date, abbr = TRUE))) %>%
  filter(TaxonName %in% Rank$TaxonName) %>% 
  group_by(Location, Month, TaxonName) %>% 
  summarise(Mean = mean(RA_Index)) %>% 
  ggplot() +
  geom_bar(aes(Month, Mean, fill = Location), stat = "identity", position = "dodge") +
  facet_wrap("TaxonName")
  
  
```



plot regions

```{r}
Indexed_UO_12S %>% 
  group_by(Location, Station_ID, Longitude, Latitude) %>% 
  summarise() %>%
  mutate(popup = paste(Location, Station_ID)) %>% 
  leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-123.1, 49.30, zoom = 11) %>% 
  addCircles(~Longitude, ~Latitude, popup = ~popup,
             weight = 4, color = "red")
  
```




```{r}
# 1. Map function
plotMat <- function(taxa, month) {
  
  m = OU_12S_Index %>% 
  group_by(TaxonName, Sample_Date, Station_ID, Latitude, Longitude) %>% 
  summarise(RA_Index = mean(RA_Index),
            RA = mean(RA),
            Seq.abundance = sum(Abundance)) %>%
  mutate(Month = month(Sample_Date)) %>%
  mutate(Popup = paste(Station_ID, "<br/>",
                       "eDNA Index: ", round(RA_Index, digits = 3), "<br/>",
                       "Relative Abundance: ", round(RA, digits = 3), "<br/>",
                       "Number of sequences: ", Seq.abundance)) %>% 
  
  filter(TaxonName == taxa,
         Month == month) %>% 
  leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-123.1, 49.30, zoom = 11) %>% 
  addCircles(~Longitude, ~Latitude, popup = ~Popup,
             weight = ~RA_Index*75, color = "red")
  return(m)

}




```



```{r}
plotMat("Clupeinae_Clupea_pallasii", 8)
plotMat("Clupeinae_Clupea_pallasii", 8)
plotMat("Clupeinae_Clupea_pallasii", 8)
plotMat("Clupeinae_Clupea_pallasii", 8)
```




Map plots
```{r}
Indexed_UO_12S %>% 
  group_by(Taxa, Date, Station_ID, Long, Lat) %>% 
  summarise(RA_Index = mean(RA_Index)*75) %>%
  mutate(Month = month(Date))
  
  filter(Taxa == "Clupeinae_Clupea_pallasii",
         Month == 8) %>% 
  leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-123.1, 49.30, zoom = 11) %>% 
  addCircles(~Long, ~Lat, popup = ~Station_ID, weight = ~RA_Index, color = "red")
```




# OLD CODE





```{r}
UO_12S
OU_12S_Index <- UO_12S %>% 
  filter(Library_ID %in% valid_samples) %>%
  mutate(Taxa = TaxonName,
         Abundance = Abundance,
         Depth = Depth,
         Date = Sample_Date) %>% 
  collapseRAindex(Library_ID, Location, Lat, Long, Station_ID)


OU_12S_Index %>%
  filter(Abundance > 0) %>%
  group_by(Taxa) %>% 
  mutate(maxRA = median(RA)) %>%
  ungroup() %>% 
  mutate(Taxa = fct_reorder(Taxa, -maxRA)) %>% 
  ggplot() +
  geom_boxplot(aes(Taxa, RA)) +
  theme_minimal_hgrid(font_size = 10) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,
                                   face = "italic"),
        panel.background = element_rect(fill = '#F5F5F5', colour = 'darkgrey')) +
  scale_y_continuous(trans='log10')


OU_12S_Index %>% 
  select(Taxa) %>% unique %>% 
  write_csv("Data_output/Taxa.csv")

```


# THIS IS WHERE THE MAP IS!!!!!

```{r}

OU_12S_Index %>% 
  group_by(Taxa, Date, Station_ID, Long, Lat) %>% 
  summarise(RA_Index = mean(RA_Index)*75) %>%
  mutate(Month = month(Date))
  
  filter(Taxa == "Clupeinae_Clupea_pallasii",
         Month == 8) %>% 
  leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-123.1, 49.30, zoom = 11) %>% 
  addCircles(~Long, ~Lat, popup = ~Station_ID, weight = ~RA_Index, color = "red")
```


```{r}
OU_12S_Index <- UO_12S %>%
  mutate(Taxa = paste(Genus, Species, sep = " ")) %>% 
  left_join(common_names, by = "Taxa") %>% 
  filter(Library_ID %in% valid_samples,
         Group != "zMultiple",
         Fish != "No") %>% 
  mutate(Taxa = Name,
         Abundance = Abundance,
         Depth = Depth,
         Date = Sample_Date) %>% 
  collapseRAindex(Library_ID, Location, Lat, Long, Station_ID)

  

```


```{r}
mat <- OU_12S_Index %>%
  #filter(month(Date) == 3) %>% 
  select(Library_ID, Taxa, RA_Index) %>% 
  pivot_wider(names_from = Taxa, values_from = RA_Index) %>% 
  column_to_rownames("Library_ID") %>% 
  as.matrix()

mod <- vegan::metaMDS(mat, trymax = 20)
plot(mod)


{  Samples <- 
    vegan::scores(mod)$sites %>% 
    as.data.frame() %>%
    rownames_to_column("Library_ID") %>% 
    mutate(Layer = "Samples")
  
  Taxa <-
    vegan::scores(mod)$species %>% 
    as.data.frame() %>%
    rownames_to_column("Taxa") %>% 
    mutate(Layer = "Taxa")
  
  NMDS_res <- bind_rows(Samples, Taxa) %>% 
    pivot_wider(names_from = Layer,
              values_from = c(NMDS1, NMDS2))
}




OU_12S_Index %>%
  #filter(month(Date) == 3) %>% 
  mutate(season = factor(month(Date))) %>% 
  left_join(NMDS_res, by = "Library_ID") %>% 
  ggplot(aes(NMDS1_Samples, NMDS2_Samples)) +
  #geom_text(aes(Taxa$NMDS1_Taxa, Taxa$NMDS2_Taxa, label = Taxa$Taxa),
   #         size = 4, colour = "white", fontface = "italic") +
  geom_point(aes(color = season), size = 3)

Taxa$NMDS1_Taxa
```


```{r}
plotNMDS <- function(x) {
  

mat <- COI_species %>%
  mutate(Depth = factor(Depth)) %>% 
  dplyr::filter(Depth %in% x) %>% 
  dplyr::select(Library_ID, Taxa, RA_Index) %>% 
  pivot_wider(names_from = Taxa, values_from = RA_Index) %>% 
  column_to_rownames("Library_ID") %>% 
  as.matrix()
  
  mat
  
mod <- metaMDS(mat, trymax = 20)

# Extract NMDS data
{  Samples <- 
    scores(mod)$sites %>% 
    as.data.frame() %>%
    rownames_to_column("Library_ID") %>% 
    mutate(Layer = "Samples")
  
  Taxa <-
    scores(mod)$species %>% 
    as.data.frame() %>%
    rownames_to_column("Taxa") %>% 
    mutate(Layer = "Taxa")
  
  NMDS_res <- bind_rows(Samples, Taxa) %>% 
    pivot_wider(names_from = Layer,
              values_from = c(NMDS1, NMDS2))
}

# Merge with metadata
COI_species %>% 
  dplyr::select(Date, Depth, Library_ID) %>%
  mutate(Month = format(as.Date(Date), format="%m"),
         Depth = factor(Depth)) %>%
  left_join(NMDS_res, by = "Library_ID") %>% 
  ggplot(aes(NMDS1_Samples, NMDS2_Samples)) +
  geom_text(aes(NMDS1_Taxa, NMDS2_Taxa, label = Taxa),
            size = 3, colour = "grey", fontface = "italic") +
  geom_point(aes(color = Month, shape = Depth), size = 3) +
  scale_color_manual(values = seasonal_colors)


}


renderPlot({
  plotNMDS(input$Filter_depth)
})

```



