---
title: "R Notebook"
output: html_notebook
---

# Prepare Data

```{r}
### SERVER: DATA PREPARATIONS AND FUNCTIONS ##### 

# Specify libraries
library(plotly)
library(ggpubr)
library(paletteer)
library(viridis)
library(cowplot)
library(leaflet)
library(readxl)
library(tidyverse)
library(vegan)
library(broom)
library(car)
library(indicspecies)
library(ggdendro)
source("Code/Functions.R")


### 1. READ IN DATA  #####

# Sequence data all
Species_table2023 <- read_csv("Data_import/Loic/12S_species_table.csv")

# Metadata from the urban oceans project
Metadata_UO <- read_excel("Data_import/Loic/VeDNA_UrbanOcean2023_sampledata.xlsx", 
    col_types = c("text", "text", "text", 
        "date", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", "text", 
        "text", "text", "numeric", "date", 
        "text", "text", "text", "numeric", 
        "text", "text", "text", "text", "numeric", 
        "text", "text", "text")) %>% 
  select(Sample_ID, Event_ID, Type, Sample_Date, Station_ID, Location,
         Line_out_depth, Bottom_depth, Latitude, Longitude)

# Metadata from the Fjords project
Metadata_Fjords <- read_csv("Data_import/Loic/01_Metadata_all.csv", 
  col_types = cols(Year = col_number())) %>% 
  filter(Survey == "FJORDS_BIODIVERSITY") %>% 
  transmute(Sample_ID = Hakai.ID,
            Event_ID = "Fjords",
            Type = "Fjords",
            Sample_Date = Date,
            Station_ID = Site_ID,
            Location = Location.ID,
            Line_out_depth = as.double(Depth),
            Bottom_depth = CTD_depth,
            Latitude = Lat,
            Longitude = Long
            )
# Merge the two metadata sets
Metadata2023 <- bind_rows(Metadata_UO, Metadata_Fjords)

# Merge metadata with sequence data
sp <- Species_table2023 %>% 
  select(!1) %>% 
  pivot_longer(!1:2, names_to = "Sample_ID", values_to = "Abundance")

All_12S_2023 <- Metadata2023 %>% 
  left_join(sp, by = "Sample_ID")



#### 2. DATA MODIFICATIONS ######

# Remove samples with low counts
Good_OU_12S <- All_12S_2023 %>% 
  group_by(Sample_ID) %>%
  filter(sum(Abundance)>10000) %>% 
  ungroup() %>% 
  
  filter(Line_out_depth == 0) %>%
  filter(Type != "FieldBlank") %>% 
  filter(month(Sample_Date) != 1)


# Data rarefaction:
Rarefied_UO_12S <- Good_OU_12S %>% 
  select(Sample_ID, scientificName, Abundance) %>% 
  pivot_wider(names_from = scientificName, values_from = Abundance, values_fill = 0) %>% 
  column_to_rownames("Sample_ID") %>% 
  rrarefy(sample = 10000) %>% 
  as.data.frame() %>% 
  rownames_to_column("Sample_ID") %>% 
  pivot_longer(!1, names_to = "scientificName", values_to = "Abundance") %>% 
  right_join(select(Good_OU_12S, !Abundance), by = c("scientificName", "Sample_ID"))





# Calculate eDNA index for all samples and species
Indexed_UO_12S <- Rarefied_UO_12S %>% 
  index_RA(sample = Sample_ID,
           taxa = scientificName,
           abundance = Abundance,
           Sample_Date, Station_ID, Location, Line_out_depth,
           Bottom_depth, Latitude, Longitude, Type)


# Rank species based on their mean relative sequence abundance, and filter low occuring species
Rank <- Indexed_UO_12S %>% 
  group_by(scientificName) %>% 
  summarise(RA = mean(RA)) %>% 
  arrange(-RA) %>% 
  filter(RA > 0.0000)

Indexed_UO_12S <- Indexed_UO_12S %>% 
  filter(scientificName %in% Rank$scientificName)

# Read in a scientific to common name translation
common_names <- read_excel("Data_output/Common_names.xlsx")

# Specify an order of sampling locations:
location_order <- c(
  "Rivers",
  "Bute",
  "Toba",
  "Howe_Sound",
  "Outer Harbour",
  "False Creek",
  "Inner Harbour",
  "Central Harbour",
  "Port Moody Arm",
  "Indian"
  )

location_names <- c(
  "Rivers Inlet",
  "Bute Inlet",
  "Toba Inlet",
  "Howe Sound",
  "Outer Harbour",
  "False Creek",
  "Inner Harbour",
  "Central Harbour",
  "Port Moody Arm",
  "Indian Arm"
  )

# Make four sampling season categories
Indexed_UO_12S <- Indexed_UO_12S %>% 
  mutate(
    Month =
      ifelse(month(Sample_Date) == 2, "Feb/Mar",
             ifelse(month(Sample_Date) == 3, "Feb/Mar",
                    ifelse(month(Sample_Date) == 5, "May",
                           ifelse(month(Sample_Date) == 8, "Aug",
                                  ifelse(month(Sample_Date) == 8, "Aug",
                                         ifelse(month(Sample_Date) == 11, "Nov",
                                                "else"))))))) %>% 
  mutate(Location = factor(Location, levels = location_order, labels = location_names))



Indexed_UO_12S <- Indexed_UO_12S %>% 
  mutate(Taxa = scientificName) %>% 
  left_join(common_names, by = "Taxa") %>% 
  filter(Fish == "Fish")








# Make list of unique Species names
all_species <- Indexed_UO_12S %>% 
  pull(Name) %>%  unique()


### PLOTTING FUNCTIONS ###

# 1. Map function
plotMat <- function(taxa, month, location) {
  
  mapplot = Indexed_UO_12S %>%
    group_by(Location, Station_ID, Month, Name) %>%
   summarise(RA_Index = mean(RA_Index),
            RA = mean(RA),
            Seq.abundance = sum(Abundance),
            Longitude, Latitude) %>%
  mutate(Popup = paste(Station_ID, "<br/>",
                       "eDNA Index: ", round(RA_Index, digits = 3), "<br/>",
                       "Relative Abundance: ", round(RA, digits = 3), "<br/>",
                       "Number of sequences: ", Seq.abundance)) %>% 
  
  filter(Name == taxa,
         Month == month) %>%
  leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  #setView(-123.1, 49.30, zoom = 11) %>% 
  addCircles(~Longitude, ~Latitude, popup = ~Popup,
             weight = ~RA_Index*75, color = "red")
  

  if (location == "Vancouver") {
    m <- mapplot %>%
      setView(-123.1, 49.30, zoom = 11)
    }
  if (location == "Lower Mainland") {
    m <- mapplot %>%
      setView(-123.1, 49.45, zoom = 9)
    }
  if (location == "British Columbia") {
    m <- mapplot %>%
      setView(-125.1, 49.90, zoom = 6)
  }
  
  return(m)

}


### END OF SERVER SCRIPT ####
```

# Beta diversity analysis

## Functions
```{r}
Location_color <- c(
  "Rivers Inlet" ='#c7eae5',
  "Bute Inlet" = '#80cdc1',
  "Toba Inlet" = '#35978f',
  "Howe Sound" = '#01665e',
  "Outer Harbour" = '#f6e8c3',
  "False Creek" = '#dfc27d',
  "Inner Harbour" = '#bf812d',
  "Central Harbour" = '#8c510a',
  "Port Moody Arm" = '#543005',
  "Indian Arm" = '#003c30'
)

Significant_color <- c(
  "Yes" = "red",
  "No" = 'black'
)


Urban <- c(
  "Outer Harbour",
  "False Creek",
  "Inner Harbour",
  "Central Harbour",
  "Port Moody Arm")

Fjords <- c(
  "Rivers Inlet",
  "Bute Inlet",
  "Toba Inlet",
  "Howe Sound",
  "Indian Arm"
)

Months <- Indexed_UO_12S %>%
  pull(Month) %>%  unique()

Locations <- Indexed_UO_12S %>%
  pull(Location) %>%  unique()

```


```{r}
Indexed_UO_12S
```








```{r}
# This function will subset the dataset based on month and location,
# and ordinate the data using NMDS.
# Outputs of the function will be a list containint a community matrix,
# a dataframe with sample variables, an NMDS model with sample scores,
# and species scores



model_NMDS <- function(month, location, norm = "eDNA-index") {

  tmp <- Indexed_UO_12S %>% 
    mutate(Environment = ifelse(Location %in% Fjords, "Fjords", "Urban"))


  if (norm == "eDNA-index") {
    wide <- tmp %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Station_ID, Location, Environment, RA_Index, Name_1) %>%
      pivot_wider(names_from = Name_1, values_from = RA_Index)
  } else {
    wide <- tmp %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Station_ID, Location, Environment, RA, Name_1) %>%
      pivot_wider(names_from = Name_1, values_from = RA)
  }
  
  # Extract Matrix
  mat <- wide %>%
    select(!2:5) %>% 
    column_to_rownames("Sample_ID") %>% 
    as.matrix()
  
  # Run NMDS
  mod <- metaMDS(mat, trymax = 100, trace = FALSE)
  
  # Extract Scores back to matri
  Species_scores <- 
    scores(mod)$species %>% 
    as.data.frame() %>%
    rownames_to_column("Species")
  
  Sample_scores <-
    scores(mod)$sites %>% 
    as.data.frame() %>%
    rownames_to_column("Sample_ID") %>% 
    left_join(select(wide, 1:5), by = "Sample_ID")
  
  list(Data = wide,
       Matrix = mat,
       Model = mod,
       Sample_scores = Sample_scores,
       Species_scores = Species_scores,
       Permanova_tab = NULL)
}

# Adding Simper results to the list produced above:

model_simper <- function(NMDS_list) {
  
  simper_result <- simper(NMDS_list$Matrix,
                          NMDS_list$Data$Environment) %>%
    summary()
  
  Simper_tab <-
    simper_result$Fjords_Urban %>%
    rownames_to_column("Species") %>%
    mutate(Significant = ifelse(p < 0.05, "Yes", "No"))
  
  NMDS_list$Species_scores <- 
    NMDS_list$Species_scores %>%
    left_join(Simper_tab)
  
  
  return(NMDS_list)
}


# Permanova model of NMDS_list

model_permanova <- function(NMDS_list) {
  
  NMDS_list$Permanova_tab <-
    adonis2(NMDS_list$Matrix ~ Location,
            data = NMDS_list$Data,
            permutations = 999, method="bray") %>% 
  tidy()
  
  return(NMDS_list)
}


# Plot_NMDS_list

plot_NMDS <- function(NMDS_list, min.sp.cont = 1, max.p = 0.05) {

  ggplot() +
    geom_point(data = NMDS_list$Sample_scores,
               mapping = aes(NMDS1, NMDS2, colour = Location),
               size = 2) +
    scale_color_manual(values = Location_color) +
    
    stat_ellipse(data = NMDS_list$Sample_scores,
                 aes(NMDS1, NMDS2, linetype = Environment), level = 0.95) +
    
    ggnewscale::new_scale_color() +
    scale_color_manual(values = Significant_color) +
    
    geom_text(data = filter(NMDS_list$Species_scores,
                            average > min.sp.cont | p <= max.p),
              mapping = aes(NMDS1, NMDS2, label = Species,
                            size = average, color = Significant)) +
    
    
    theme_minimal_grid(12) +
    theme(aspect.ratio = 1,
          panel.border = element_rect(colour = "black", fill=NA)) 
}




# Plot dendrogram
plot_hclust <- function(NMDS_list) {
  
  # Step 1: Create distance matrix and hierarchical clustering
  # Step 2: Convert hclust to dendrogram and then to ggplot-friendly format
  dend_data <- NMDS_list$Matrix %>% 
    vegdist() %>% 
    hclust() %>% 
    dendro_data()
  
  # Step 3: Join location information to the dendrogram segments
  # Create a data frame that maps each segment to a location
  segment_data <- dend_data$labels %>% 
    left_join(NMDS_list$Data, by = c("label" = "Sample_ID"))
  
  
  # Map colors based on Location
  Location_color
  
  # Step 4: Plot dendrogram in ggplot
  ggplot() +
    geom_segment(data = dend_data$segments, aes(x = x, y = y, xend = xend, yend = yend), color = "grey") +
    geom_text(data = segment_data, aes(x = x, y = y, label = Station_ID), vjust = 0.5, hjust = -0.2) +
    geom_point(data = segment_data, aes(x = x, y = y, color = Location), size = 4) +
    scale_color_manual(values = Location_color) +
    labs(color = "Location") +
    theme_minimal() +
    coord_flip() +
    scale_y_reverse(expand = c(0.2, 0))  # Flipping to make it look like a standard dendrogram
  
}






```




## Global Analysis (Urban and Fjords)

### All months

```{r}
All <- model_NMDS(Months, Locations, "eDNA-index") %>% 
  model_simper()

# NMDS
plot_NMDS(All, min.sp.cont = 0.05, max.p = 0.05)


# Permanova
perm_all <- adonis2(All$Matrix ~ Location * Month,
            data = All$Data,
            permutations = 999, method="bray") %>% 
  tidy()
perm_all

# Dispersion analysis
dispersion <- All$Matrix %>% 
  vegdist(method = "bray") %>% 
  betadisper(group = All$Data$Environment)

boxplot(dispersion, main = "Beta Dispersion by Group")
permutest(dispersion)

# Indicator species analysis
ind_mod <- multipatt(All$Matrix, All$Data$Environment, func = "IndVal.g")
summary(ind_mod)
```

### Feb 
```{r}
Feb <- model_NMDS("Feb/Mar", Locations, "Relative Abundance") %>% 
  model_simper()

plot_NMDS(Feb, min.sp.cont = 0.02, max.p = 0.05)

model_permanova(Feb)

dispersion <- Feb$Matrix %>% 
  vegdist(method = "bray") %>% 
  betadisper(group = Feb$Data$Environment)

boxplot(dispersion, main = "Beta Dispersion by Group")
permutest(dispersion)

# Indicator species analysis
ind_mod <- multipatt(Feb$Matrix, Feb$Data$Environment, func = "IndVal.g")
summary(ind_mod)

# Hclust
plot_hclust(Feb)
```
### May
```{r}
May <- model_NMDS("May", Locations, "Relative Abundance") %>% 
  model_simper()
plot_NMDS(May, min.sp.cont = 0.02, max.p = 0.05)
model_permanova(May)


dispersion <- May$Matrix %>% 
  vegdist(method = "bray") %>% 
  betadisper(group = May$Data$Environment)

boxplot(dispersion, main = "Beta Dispersion by Group")
permutest(dispersion)

# Indicator species analysis
ind_mod <- multipatt(May$Matrix, May$Data$Environment, func = "IndVal.g")
summary(ind_mod)

# Hclust
plot_hclust(May)
```

### Aug
```{r}
Aug <- model_NMDS("Aug", Locations, "Relative Abundance") %>% 
  model_simper()
plot_NMDS(Aug, min.sp.cont = 0.02, max.p = 0.05)
model_permanova(Aug)

dispersion <- Aug$Matrix %>% 
  vegdist(method = "bray") %>% 
  betadisper(group = Aug$Data$Environment)

boxplot(dispersion, main = "Beta Dispersion by Group")
permutest(dispersion)

# Indicator species analysis
ind_mod <- multipatt(Aug$Matrix, Aug$Data$Environment, func = "IndVal.g")
summary(ind_mod)


# Hclust
plot_hclust(Aug)
  
```



### Nov
```{r}
Nov <- model_NMDS("Nov", Locations, "Relative Abundance") %>% 
  model_simper()
plot_NMDS(Nov, min.sp.cont = 0.02, max.p = 0.05)
model_permanova(Nov)

dispersion <- Nov$Matrix %>% 
  vegdist(method = "bray") %>% 
  betadisper(group = Nov$Data$Environment)

boxplot(dispersion, main = "Beta Dispersion by Group")
permutest(dispersion)

# Indicator species analysis
ind_mod <- multipatt(Nov$Matrix, Nov$Data$Environment, func = "IndVal.g")
summary(ind_mod)

plot_hclust(Nov)

```



```{r}



```



## Urban Ocean only






# Alpha diversity analysis

## Data rarefaction:


```{r}
WIDE <- Indexed_UO_12S %>%
  select(Sample_ID, Sample_Date, Station_ID, Location, Line_out_depth, Month, Type, Name_1, Abundance) %>% 
  pivot_wider(names_from = Name_1, values_from = Abundance, values_fill = 0)
WIDE  

MAT <- WIDE %>%
  column_to_rownames("Sample_ID") %>% 
  select(!1:6)

set.seed(123)  # Set seed for reproducibility
data_rarefied <- rrarefy(MAT, sample = 20000)

data_rarefied


```


```{r}
Alpha_diversity <-
  tibble(Sample_ID = rownames(data_rarefied),
         Richness = specnumber(data_rarefied),
         Shannon_Index = diversity(data_rarefied, index = "shannon"),
         Simpson_Index = diversity(data_rarefied, index = "simpson"),
         Evenness = diversity(data_rarefied, index = "shannon") / log(specnumber(data_rarefied))
       
       ) %>% 
  left_join(select(WIDE, 1:7)) %>% 
  mutate(Month = factor(Month, levels = Months))

Alpha_diversity %>%
  ggplot() +
  geom_boxplot(aes(Location, Shannon_Index, colour = Month))

anova_model <- aov(Shannon_Index ~ Month * Type, data = Alpha_diversity)
summary(anova_model)
plot(anova_model)

library(lme4)
lmm_model <- lmer(Shannon_Index ~ Month + Type + (1 | Location), data = Alpha_diversity)
summary(lmm_model)

Alpha_diversity
```





# Plot map - non complete!

```{r}

library(ggOceanMaps)
library(ggspatial)
library(patchwork)
library(sf)


canada_ocean <- st_read("Data_import/lhy_000h16a_e/lhy_000h16a_e.shp")

ggplot() +
  geom_sf(data = canada_ocean, fill = "lightblue")

# If necessary, crop the shapefile to a smaller extent
# Define the bounding box for Vancouver area (example coordinates)
bbox <- st_bbox(c(xmin = -124, xmax = -122, ymin = 49, ymax = 50), crs = st_crs(canada_ocean))



lims <- c(-129, -120, 48, 53)
basemap(limits = lims, rotate = TRUE)
canada_coast <- rgdal::readOGR("Data_import/lhy_000h16a_e/lhy_000h16a_e.shp")
BC_coast <- clip_shapefile(canada_coast, lims)
BC_coast <- list(land = BC_coast, glacier = NULL, bathy = NULL)

basemap(shapefiles = BC_coast, limits = c(-124, -120, 48, 53), rotate = TRUE)
```


```{r}
# 1. Draw inner map with points for stations

# Make a dataframe cointatining staion coordinates
pin <- Indexed_UO_12S %>% 
    mutate(Environment = ifelse(Location %in% Fjords, "Fjords", "Urban")) %>% 
   group_by(Location, Station_ID, Environment) %>% 
   summarise(lon = mean(Longitude),
             lat = mean(Latitude)) %>% 
   filter(Environment == "Urban")

# Plot inner map
inner <-
  # Define the limits (zoom of the map)
  basemap("GEBCO", limits = c(-124, -122, 49, 50), rotate = TRUE) +
  # Add red point for sampling station(s)
  geom_spatial_point(data = pin, aes(x = lon, y = lat), color = "red", size = 2) +
  # Add station labels, but adjuest position to not cover the point.
  geom_spatial_label(data = pin, aes(x = lon-0.35, y = lat-0.15, label = Station_ID)) +
  # Remove axis title
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank())

inner

"~/ggOceanMapsLargeData"


```


```{r}
# 2. Draw outer map with box highlighting the inner map.

# Make a dataframe cointatining 4 coordinates defining box corners.
# Use same coordingates as the limits defined above.
insert_box <- data.frame(lon = c(-126.5, -126.5, -121.8, -121.8),
                         lat = c(48.3, 51.3, 51.3, 48.3))
# Plot outer map
outer <-
  # Define the limits (zoom of the map)
  basemap(limits = c(-130.0, -80.0, 35.0, 75.0), rotate = TRUE) +
  # Draw polygon for inner map
  geom_spatial_polygon(data = insert_box, aes(x = lon, y = lat),
                       fill = NA, color = "red") +
  # Remove axis title
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank())


# 3. Make outer plot as insert of inner. Define size and location.
final_map <- inner + inset_element(outer, 0.5, 0.5, 1, 1)

final_map


```




# Legacy

```{r}

plotNMDS <- function(month, location, norm) {

  tmp <- Indexed_UO_12S %>% 
    mutate(Environment = ifelse(Location %in% Fjords, "Fjords", "Urban"))


  if (norm == "eDNA-index") {
    wide <- tmp %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Location, Environment, RA_Index, Name) %>%
      pivot_wider(names_from = Name, values_from = RA_Index)
  } else {
    wide <- tmp %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Location, Environment, RA, Name) %>%
      pivot_wider(names_from = Name, values_from = RA)
  }

# Extract Matrix
mat <- wide %>%
    select(!2:4) %>% 
    column_to_rownames("Sample_ID") %>% 
    as.matrix()

# Run NMDS
mod <- metaMDS(mat, trymax = 100, trace = FALSE)

# NEW
Species_scores <- 
  scores(mod)$species %>% 
  as.data.frame() %>%
  rownames_to_column("Species")

# SIMPER
simper_result <- simper(mat, group = wide$Environment) %>% 
  summary()

Simper_tab <- simper_resul[1] %>%
  rownames_to_column("Species")

Top_Species <- Simper_tab %>% 
  filter(average > 0.01) %>% 
  pull(Species)
  

# Extract Scores back to matrix
Sample_scores <-
    scores(mod)$sites %>% 
    as.data.frame() %>%
    rownames_to_column("Sample_ID") %>% 
    left_join(select(wide, 1:4), by = "Sample_ID")


NMDS_plot <- Sample_scores %>% 
  ggplot() +
  geom_point(mapping = aes(NMDS1, NMDS2, colour = Location),
             size = 3) +
  stat_ellipse(aes(NMDS1, NMDS2, linetype = Environment), level = 0.95) +
  geom_text(data = filter(Species_scores, Species %in% Top_Species),
            mapping = aes(NMDS1, NMDS2, label = Species)) +
  theme_minimal_grid(12) +
  theme(aspect.ratio = 1,
        panel.border = element_rect(colour = "black", fill=NA)) +
  scale_color_manual(values = Location_color)


Permanova_tab <- adonis2(mat ~ Location+Month,
                       data = wide,
                       permutations = 999, method="bray") %>% 
  tidy()

list(NMDS_plot,
     Permanova_tab,
     Simper_tab,
     Sample_scores,
     Species_scores,
     Data = wide)

}





```



```{r}

printPERMANOVA <- function(month, location, norm) {

  if (norm == "eDNA-index") {
    wide <- Indexed_UO_12S %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Location, RA_Index, Name) %>%
      pivot_wider(names_from = Name, values_from = RA_Index)
  } else {
    wide <- Indexed_UO_12S %>%
      filter(Month %in% month,
             Location %in% location) %>%
      select(Sample_ID, Month, Location, RA, Name) %>%
      pivot_wider(names_from = Name, values_from = RA)
  }

# Extract Matrix
mat <- wide %>%
    select(!2:3) %>% 
    column_to_rownames("Sample_ID") %>% 
    as.matrix()


adonis2(mat ~ Location,
                       data = wide,
                       permutations = 999, method="bray") %>% 
  tidy()
}
```


